# Generated by Django 5.2.7 on 2026-09-11 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='monthly_limit',
            new_name='weekly_limit',
        ),
    ]
